### ISSUE TITLE
Upgrade RabbitMQ version

### ISSUE THREAD

**Issue by ytimocin** [radius-project/recipes#55]
## Overview of feature request
Seeing this message in one of the **rabbitMQ** pod logs: `This release series has reached end of life and is no longer supported. Please visit https://rabbitmq.com/versions.html to learn more and upgrade.`

## Acceptance criteria
RabbitMQ version needs to be upgraded.

Please see this page: https://rabbitmq.com/versions.html.

## Additional context
```
2023-11-23 00:10:57.202383+00:00 [info] <0.223.0>  Starting RabbitMQ 3.10.25 on Erlang 25.3.2.7 [jit][0m
2023-11-23 00:10:57.202383+00:00 [info] <0.223.0>  Copyright (c) 2007-2023 VMware, Inc. or its affiliates.[0m
2023-11-23 00:10:57.202383+00:00 [info] <0.223.0>  Licensed under the MPL 2.0. Website: https://rabbitmq.com[0m
[38;5;160m2023-11-23 00:10:57.202455+00:00 [error] <0.223.0> This release series has reached end of life and is no longer supported. Please visit https://rabbitmq.com/versions.html to learn more and upgrade[0m
```

[AB#10476](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10476)

**Comment by AaronCrawfis** [comment]
We currently use the tag `3` in the rabbitmq local-dev recipe, which pulls the latest major version from Dockerhub. As of today, it pulled 3.12 for me, which is in support.

I suspect you might have a cached version of the rabbitmq image from back when 3.10 was tagged `3`. If you're using the same Kubernetes cluster as back then it may pull the same image.

If you still hit this after evicting your old image, or on a new cluster, please reopen with steps on how to reproduce.
