### ISSUE TITLE
rad recipe registration

### ISSUE THREAD

**Issue by kevinevans1** [radius-project/recipes#61]
### Steps to reproduce (required)

```
rad init
                                                     
Initializing Radius. This may take a minute or two...
                                                     
✅ Use existing Radius 0.29.0 install on microk8s    
✅ Use existing environment default                  
✅ Scaffold application terraform                    
✅ Update local configuration                        
                                                     
Initialization complete! Have a RAD time 😎     
```

### Observed behavior (required)
rad recipe register myrecipe --environment myenv --resource-type Applications.Datastores/redisCaches --template-kind terraform --template-path recipes/terraform --template-version "1.1.0"
Error: {
  "code": "NotFound",
  "message": "the resource with id '/planes/radius/local/resourcegroups/default/providers/Applications.Core/environments/myenv' was not found",
  "target": "/planes/radius/local/resourcegroups/default/providers/Applications.Core/environments/myenv"
}

TraceId:  f2e3f6eec52768e337ad59e3f5b95559

### Desired behavior (required)
terraform to be registered in local radius dev cluster

### Workaround (optional)
n/a

### rad Version (required)
0.29

rad version
RELEASE   VERSION   BICEP     COMMIT
0.29.0    v0.29.0   0.29.0    6abd7bfc3de0e748a2c34b721d95097afb6a2bba
### Operating system (required)
Windows 11 23H2 with WSL

## Additional context
Could be a user error :)

AB#12067

**Comment by AaronCrawfis** [comment]
Thanks for reporting @kevinevans1! Looks like an issue with the resource group or environment.

In your rad init example it looks like you have an environment named `default`, but in the registration step you were referencing an environment named `myenv`. If you're using your default environment, could you try the following command to address default instead of myenv?

```bash
rad recipe register myrecipe --environment default --resource-type Applications.Datastores/redisCaches --template-kind terraform --template-path recipes/terraform --template-version "1.1.0"
```

**Comment by Reshrahim** [comment]
@kevinevans1 - Were you able to rectify this user error and make progress ?

**Comment by sylvainsf** [comment]
Seems to be resolved/no reproducible steps.
